### ISSUE TITLE
Validation doens't check the variables

### ISSUE THREAD

**Issue by entropitor** [graphql-community/koa-graphql#106]
When there is a validation errors in the variables, a 200 is returned instead of a 400

**Comment by chentsulin** [comment]
Hi @entropitor 
Could you write a failed test to demonstrate this issue?
Now, there is a test shows that it response stats 400 when receive validation error:
https://github.com/chentsulin/koa-graphql/blob/7b4d23aecf5926c9b0181d6e9e775d2a1357c9d1/src/__tests__/http-test.js#L201-L225

**Comment by entropitor** [comment]
@chentsulin You are testing the validations on the query, then it correctly returns a 400, but if there is a validation error on the variables (e.g. the value of a variable not matching the given type) then it returns a 200.

I can see if I can write a test myself soon

**Comment by chentsulin** [comment]
The codebase has been changed a lot, so this might not be reproduced anymore.
