### ISSUE TITLE
graphiql support for subscriptions endpoint

### ISSUE THREAD

**Issue by sibelius** [graphql-community/koa-graphql#110]
Can we do something like this:  https://github.com/janie128/subscription-graphql/blob/master/server/index.js#L18-L21?

using koa-graphql?

**Comment by ronal2do** [comment]
+ 1

**Comment by chentsulin** [comment]
It's reasonable. I will look into this later if no anyone take this.

**Comment by evseevnntmp** [comment]
Any update

**Comment by respinha** [comment]
Any update?

**Comment by Max-Starling** [comment]
Any update?

**Comment by prakasa-tkpd** [comment]
any update on this ?
