### ISSUE TITLE
0.8.0 returns 500 on errors from GraphQLScalarType/parseValue

### ISSUE THREAD

**Issue by giannisp** [graphql-community/koa-graphql#118]
Use case:
Throw a `GraphQLError` as part of a validation on a custom `GraphQLScalarType`.

0.8.0:
`parseValue`: returns a 500 response
0.7.5:
`parseValue`: returns 200 and the actual `errors` from GraphQL

**Comment by chentsulin** [comment]
This should be fixed in the latest release:
https://github.com/graphql-community/koa-graphql/releases/tag/v0.12.0
