### ISSUE TITLE
[flow] type error

### ISSUE THREAD

**Issue by HsuTing** [graphql-community/koa-graphql#120]
I am using `koa-graphql` with `flow`, and it throw error with `can not find module "express"`.
Because `express-graphql` import `express` with `flow`, we need to install `express` in the project. However, we use `koa`, not `express`, this is strange.

**Comment by HsuTing** [comment]
I found the another problem that`koa-graphql` can not work with `koa_v2.0.x` in `flow-typed`.

**Comment by chentsulin** [comment]
We're writing the whole codebase with TypeScript, so flowtype support is not officially supported in this repo.
