### ISSUE TITLE
Status of this Module?

### ISSUE THREAD

**Issue by vanthome** [graphql-community/koa-graphql#122]
Hi, what is the status of this module, there are some upgrades due by now I think and as active user I'm a bit concerned.
BG

**Comment by yanickrochon** [comment]
Yes, I'm looking for a suitable module to integrate with you current Koa app and 2 years is indeed concerning.

**Comment by sibelius** [comment]
@chentsulin can add more maintainers or contributors

I can help

**Comment by yanickrochon** [comment]
@sibelius I think one way would be to fork and create PR that people can use. Having an updated module would be an incentive for more usage to begin with. Because considering the current situation, I'm tempted to use the express module and wrap it in Koa. Ew.

**Comment by sibelius** [comment]
what about moving to https://github.com/graphql-community?

@chentsulin are you open to this?

**Comment by yanickrochon** [comment]
I think it should be hosted at the same place as `express-graphql`, no? i.e. [GraphQL](https://github.com/graphql)

**Comment by chentsulin** [comment]
@sibelius The transfer to the graphql-community org has been completed.

**Comment by sibelius** [comment]
@chentsulin thanks, can you add me to npm to publish a new version?

I've also added @yanickrochon and @vanthome as contributors to help with issues, pull requests and updates

**Comment by justinfagnani** [comment]
@sibelius @chentsulin did you ever get npm permissions sorted out to publish new versions?

Fixing issues like #136 would be very welcome.
