### ISSUE TITLE
The graphiql property doesn't allow assigning any value with type other than a boolean (TypeScript).

### ISSUE THREAD

**Issue by ivantokar** [graphql-community/koa-graphql#131]
- Typescript: 3.9.3
- koa-graphql: 0.8.0
- @types/koa-graphql: 0.8.3

I'm tried to set up the "Darkula" theme for GraphiQL following this manual: [Custom GraphiQL themes](https://github.com/graphql-community/koa-graphql#custom-graphiql-themes), but get an error about a type.

`Type '{ editorTheme: string; }' is not assignable to type 'boolean'.`

**Code**
```ts
graphqlHTTP({
    schema,
    graphiql: {
        editorTheme: 'darkula',
    },
})
```
**Type definitions**
```ts
    /**
     * A boolean to optionally enable GraphiQL mode.
     */
    graphiql?: boolean;
```

**Comment by Alexsey** [comment]
The Readme is talking about the feature that is present in master and it has been merged there a little bit more than a month ago while 0.8 version has been released one and a half years ago. The simplest option I can think about would be to use github master instead of npm version

**Comment by ivantokar** [comment]
> The Readme is talking about the feature that is present in master and it has been merged there a little bit more than a month ago while 0.8 version has been released one and a half years ago. The simplest option I can think about would be to use github master instead of npm version
> 
> UPD: it should be safe because since 0.8 release this is the only change to the code except of dependency updates

Thank you so much, not a big deal. This default theme is fully enough to work. I will wait a bit.

**Comment by chentsulin** [comment]
This issue should be fixed by https://github.com/graphql-community/koa-graphql/releases/tag/v0.12.0 which brings built-in TypeScript support to the package.
