### ISSUE TITLE
Perform mutation on GET

### ISSUE THREAD

**Issue by jgcmarins** [graphql-community/koa-graphql#134]
Hello, thanks for this awesome lib.
Are there any special reasons for not allowing mutations on GET?
https://github.com/graphql-community/koa-graphql/blob/4d6d9c302caab7c1c47a58e2a17fba21b621fe3f/src/index.js#L229-L249

**Comment by chentsulin** [comment]
Hi @jgcmarins, that's because this lib is basically a koa port of `express-graphql` and it doesn't allow sending mutations on GET. 

https://github.com/graphql/express-graphql/blob/28e4c2924ea6984bf918465cefdadae340d8780e/src/index.ts#L301-L319
