### ISSUE TITLE
Versions 0.9.0 and 0.10.0 are not published

### ISSUE THREAD

**Issue by shellbj** [graphql-community/koa-graphql#142]
Latest version available is only 0.8.0:
https://www.npmjs.com/package/koa-graphql

**Comment by sibelius** [comment]
migrate to Helix https://github.com/contrawork/graphql-helix

**Comment by shellbj** [comment]
If this project is dead, then please update the README to reflect it's status.

**Comment by chentsulin** [comment]
Hey @shellbj I can't find anything about versions 0.9.0 and 0.10.0 in our commits and releases history:
https://github.com/graphql-community/koa-graphql/commits/master
https://github.com/graphql-community/koa-graphql/releases

Where did you find them?

**Comment by chentsulin** [comment]
Oh, I see. There are changes in the `package.json` file.

**Comment by chentsulin** [comment]
These latest changes have been published in https://github.com/graphql-community/koa-graphql/releases/tag/v0.9.0
